name: Demo Workflow
on: workflow_dispatch
jobs: 
  print:
    runs-on: windows-latest
    steps:
      - name: Print to console
        run: echo Helllo GH Actions!
      - name: Print a few lines
        run: |
          echo First!
